### ISSUE TITLE
Opening previously created files

### ISSUE THREAD

**Issue by clamport** [lewish/asciiflow2#102]
I can't seem to open previously created files. If I click the drive icon and click a different file, it attempts to save the current file to the selected file. If I go to google drive and attempt to open the file, it attempts to open it as a google doc file.

How do we re-open saved flows?

**Comment by Qix-** [comment]
Google drive import/export isn't working right now, I have it on my list to address it.

**Comment by Qix-** [comment]
Duplicate of #118.
