### ISSUE TITLE
V becomes ^ when v is directly above another v

### ISSUE THREAD

**Issue by client4** [lewish/asciiflow2#103]
In text mode, a "v" is turned into "^".

**Comment by whj2819** [comment]
me too

**Comment by rawlk** [comment]
Seems to also be filed in https://github.com/lewish/asciiflow2/issues/96 , #82, #52

**Comment by Qix-** [comment]
Duplicate of #109. Fixed and published already, go check it out :)

**Comment by eeliu** [comment]
###  Does it fix ?

![图片](https://user-images.githubusercontent.com/27064129/55069647-7ac1af00-50bf-11e9-889b-9d8a42f1cceb.png)

**Comment by Qix-** [comment]
Neat, good catch @eeliu.

**Comment by mort3za** [comment]
I think it's better to use these unicode characters for arrow shapes:
```
˄ ˅
&#x2C4; and &#x2C5; respectively.
```

**Comment by lewish** [comment]
Pretty sure this is fixed now.
