### ISSUE TITLE
Permalink support

### ISSUE THREAD

**Issue by ben-albrecht** [lewish/asciiflow2#104]
The existing import / export / Drive support is useful, but a simple permalink feature would be really convenient for saving and sharing asciiflows.

**Comment by Qix-** [comment]
Problem is, the permalink would require encoding the entire diagram into the URL, which could potentially yield _really_ long URLs. If that's okay with you, then great. But a referenced permalink, where we store the data and give you an ID, is out of the question - we use Github pages to host, which is free and has no server-side component.

I'll think about this a bit about how to make the URLs a bit shorter.

**Comment by lewish** [comment]
Yo, I've done this now. Indeed was tricky, I'm using pako to inflate/deflate the text, and this seems to keep most reasonable drawings under browser limits (2K?).

Here's an example:

https://asciiflow.com/#/share/eJyrVspLzE1VssorzcnRUcpJrEwtUrJSqo5RqohRsrI0N9GJUaoEsowsQKyS1IoSICdGSQECHk3ZQyqKiclDaFZABZgicFABBUDtuEzGNIwYhGIJzC6ILcQ5E7sZCuhmkIpItAEfoIt%2BMrxIAE3DGh44bQ%2FJyCxWAKJEhZSixPLMvHQ0lxNjBiHfDyUzaIpgllbgsBybo3F5AWJIBUVmKBAsHR5N20WUgYjyiWg3oGqhKYpRqlWqBQD6bFlJ)

**Comment by ben-albrecht** [comment]
Looks very nice. Thanks @lewish!
