### ISSUE TITLE
Rulers for lines & columns

### ISSUE THREAD

**Issue by lamawithonel** [lewish/asciiflow2#105]
It would be useful to have graduated rulers along the sides of the screen showing the number of lines and columns.  The added information would be helpful where the audience screen size is limited, or where regular, evenly-spaced lines are required.

See also #44.

**Comment by Qix-** [comment]
Not sure how this would work given that it doesn't really matter what the origin point is.

What are you hoping to gain from these rulers? Width/height information?

**Comment by Qix-** [comment]
Conjoining this with #44 as AF3 already has this planned and I agree it's a much-needed feature.

Sorry for the noise!
