### ISSUE TITLE
Importing characters incorrectly.

### ISSUE THREAD

**Issue by stevepeak** [lewish/asciiflow2#112]
> Thanks for a really amazing product 👍 

Found that `v` turns into `^` during importing.
https://cl.ly/2k3v0F3Y3b1x

**Comment by michkot** [comment]
Confirm, happens even when writing new text (I have diacritics in the text if that might be problem)

**Comment by Qix-** [comment]
Duplicate of #109. Fixed and published already, go check it out :)
