### ISSUE TITLE
Feature request: Other shapes

### ISSUE THREAD

**Issue by eddieSullivan** [lewish/asciiflow2#113]
First of all, fantastic job. This is a great tool and great concept.

But of course, your "reward" for making something so useful is people always want more. ;)

It would be awesome if you could add other flow-chart shapes, like for showing a decision point:

```
    ^
  /   \
 |     |
  \   /
    v
```

or something like that.

**Comment by Qix-** [comment]
I'm not sure how in-scope this is, it would be hard to pull off from an implementation standpoint, as well as the fact that it doesn't translate well into unicode characters.

Neat idea though :)
