### ISSUE TITLE
Inconsistent Line Intersections

### ISSUE THREAD

**Issue by jlogix** [lewish/asciiflow2#115]
Thank you for this wonderful tool!

I would really appreciate if you could use '+' character at all line intersections consistently. Please see an example below. Notice that there is no  '+' where the two lines intersect.

```
+--------------------+---------+
|                    |         |
|                    |         |
|                    |         |
|                    |         |
+--------+---------------------+
|        |           |         |
|        |           |         |
|        |           |         |
|        |           |         |
+--------+-----------+---------+

```

**Comment by Qix-** [comment]
Interesting, reproduced. I agree this is a bug.

**Comment by rawlk** [comment]
For what its worth, I use the fact that you can 'punch through' certain lines and intersect with others. I've used it to show that X connects to Y within Z host

![image](https://user-images.githubusercontent.com/5741202/52586416-155e7b00-2dfd-11e9-8d14-749d0a9ae33f.png)

**Comment by Qix-** [comment]
Yes this occurred to me as well shortly after I posted the above comment. I'm thinking maybe holding a modifier key could affect which strategy it chooses, _while_ you're drawing the line.

**Comment by lewish** [comment]
Should be fixed now in the new version

![image](https://user-images.githubusercontent.com/912458/109414104-07123600-79a9-11eb-9b6d-2809e45e7fe9.png)

Which exports to vanilla ascii text as:

```
+--------------------+---------+
|                    |         |
|                    |         |
|                    |         |
|                    |         |
+--------+-----------+---------+
|        |           |         |
|        |           |         |
|        |           |         |
|        |           |         |
+--------+-----------+---------+
```
