### ISSUE TITLE
Google Drive auth does not work with "This app has not been verified yet by Google"

### ISSUE THREAD

**Issue by nobuto-m** [lewish/asciiflow2#118]
When trying to use Google Drive, it fails when authenticating against Google. The error messages are below:

```
Sign in with Google temporarily disabled for this app

This app has not been verified yet by Google in order to use Google Sign In.
```
![google](https://user-images.githubusercontent.com/4356209/43408738-087aaa56-945d-11e8-883d-25baa306b35f.png)

**Comment by mikeal** [comment]
Any movement on this?

I know a few people at Google in Cloud that might be able to get push this through if there is an issue.

**Comment by glshnu** [comment]
i have the same problem - do you plan to support onedrive?

**Comment by AaronBeaudoin** [comment]
Can we get this fixed please?

**Comment by caleb-allen** [comment]
Also experiencing this

**Comment by tmoonlight** [comment]
cant save，hurry to fix it pls...

**Comment by Arakade** [comment]
@Qix- Please might you post a little something here about what might happen for this?

A lack of anything feels like the project is abandoned which I'm sure its happy users hope isn't the case.  Is it a case of needing something other than code?  Perhaps describing here might let someone who can help provide that know and act?  (like the query from @mikeal above)

I don't use often but when I need an ASCII diagram, this is my go-to.  It's not perfect but it *is* good.

Thank you for your work on it so far and any response :)

**Comment by Qix-** [comment]
@Arakade see #150 :) Sorry for the noise.

**Comment by lewish** [comment]
Google drive integration has now been removed.
