### ISSUE TITLE
Inserting text box with v character, v converted to ^

### ISSUE THREAD

**Issue by ddevienne** [lewish/asciiflow2#121]
Somehow v characters are converted to carets. Weird.
Was writing Save, and appeared on canvas as Sa^e.

Great little tool BTW. Thanks!

PS: I can't seem to move text, once on the canvas. Quite inconvenient
PPS: I'd love more line and arrow "styles", especially thicker ones.

**Comment by bigjosh** [comment]
Same thing here! Seems to be 100% reproducible if the 'v' in on the second line like here...
![image](https://user-images.githubusercontent.com/5520281/47669327-138be700-db81-11e8-9135-13847a5b425a.png)

+1 for wide lines! 

... and LOVE this tool! Thanks!

**Comment by Qix-** [comment]
Duplicate of #109. Fixed and published already, go check it out :)

**Comment by Qix-** [comment]
Interesting, can you open a new issue @ddevienne? :)

**Comment by ddevienne** [comment]
Sure. I opened #130.
