### ISSUE TITLE
Should reverse Upload and Download icon?

### ISSUE THREAD

**Issue by icyhat** [lewish/asciiflow2#122]
Well, this is an nice tool to draw plain text chart.
But why when I wanna download my draw and it just disappeared due to the Universal Download Icon was meat to be a Upload Icon as a User Friendly Design?
What the hell of that design?

**Comment by Qix-** [comment]
If you're referring to these:
![image](https://user-images.githubusercontent.com/885648/52585329-bd436b00-2e34-11e9-9797-a25fb0e6b8ee.png)
Then I agree - I've always felt they were backwards as well.

**Comment by lewish** [comment]
Flipped this in AF3!
