### ISSUE TITLE
Copy/paste support

### ISSUE THREAD

**Issue by JJonesAtAvaya** [lewish/asciiflow2#125]
I love this tool, please add copy and paste, ty

**Comment by Qix-** [comment]
This is already a thing. You just have to use the regular cursor to select, then you can copy with the keyboard shortcut Ctrl+C (windows) or Cmd+C (mac), use the cursor to select a single cell for the new position, and use Ctrl+V (windows) or Cmd+V (mac) to paste.

![kapture 2019-02-11 at 19 04 00](https://user-images.githubusercontent.com/885648/52583632-5c199880-2e30-11e9-9c13-88b5d284db42.gif)
