### ISSUE TITLE
Add mermaid support

### ISSUE THREAD

**Issue by JJonesAtAvaya** [lewish/asciiflow2#126]
If this could somehow be combined with mermaid, I'd be thrilled!

https://github.com/knsv/mermaid

**Comment by Qix-** [comment]
I'll think about this one. :) Not a concrete 'no', yet.

**Comment by jgroom33** [comment]
i see this as a replacement for mermaid for several use cases

**Comment by Qix-** [comment]
Yeah I don't see this making much sense. Thanks for the suggestion though :)
