### ISSUE TITLE
Dream feature request

### ISSUE THREAD

**Issue by JJonesAtAvaya** [lewish/asciiflow2#127]
If I could drag this in:
![image](https://user-images.githubusercontent.com/45052269/50309746-cf1c1980-0454-11e9-922d-7ca68b329f37.png)
and it would generate something like this:
![image](https://user-images.githubusercontent.com/45052269/50309822-186c6900-0455-11e9-86c6-f3dc6ddb1596.png)

**Comment by Qix-** [comment]
That's not going to happen I don't think. The amount of code and image recognition that would have to happen would be a feat on its own.

Sorry 😓
