### ISSUE TITLE
v characters displayed with different background. All v's sandwiched in angle-brackets

### ISSUE THREAD

**Issue by ddevienne** [lewish/asciiflow2#130]
As a follow-up to #121, as shown below, and explained in above title.
Regarding the second issues, I was _monkey_ typing all v's, and I can't tell if the brackets were added, or if they replaced v's I typed.

![image](https://user-images.githubusercontent.com/219319/52634497-a9951480-2ec7-11e9-8cab-12352df89058.png)

**Comment by Qix-** [comment]
I would wager they were replaced.

This will be fixed in Asciiflow3.

**Comment by Qix-** [comment]
Merging into #103 as it's the same class of issue. Sorry for the noise!
