### ISSUE TITLE
'<<' turned into '<>'

### ISSUE THREAD

**Issue by stillwondering** [lewish/asciiflow2#131]
It's not possible to add a text box saying `<<interface>>`. `<<` and `>>` is always turned into `<>`.

![image](https://user-images.githubusercontent.com/44878817/54428795-dfbff100-471e-11e9-8d3d-5de84dbc7823.png)

**Comment by hexmind** [comment]
And `email-validator` is turned into `email->alidator`.

**Comment by Qix-** [comment]
Yeah this is something v3 will fix.

**Comment by Qix-** [comment]
Merging into #103 as it's the same class of issue. Sorry for the noise!
