### ISSUE TITLE
Google login popup keeps popping up

### ISSUE THREAD

**Issue by DaanBiesterbos** [lewish/asciiflow2#136]
I just finished a chart, tried to export is to google. Got an error that the app was not authorized yet. Closed the window. And the login window kept popping up, when I closed it, it came back instantly. This made it impossible to save or export my work. I had to reload the page, hoping there was at least something that would store the chart in local storage or whatever. But nope. Chart is gone. 

I do like the idea of this editor. Great for textual documentation. I'd like to hear it when the product  is actually usable. 

Daan

**Comment by ShaneOH** [comment]
I ran into this same problem. Managed to move aside/minimize the window just long enough to click "export" (then minimize the next pop-up again) then copy the text (spawning another popup) then paste it into an external editor, then had to reload the page and import the text back in, taking care not try click the Drive button again (which will definitely break the page with infinite pop-ups) 

Hope that temp solution saves anyone else from losing their work if they come across this!

**Comment by Qix-** [comment]
Mostly duplciate of #118. Anything not covered there, please leave a comment.
