### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by jgroom33** [lewish/asciiflow2#137]
codeblocks with `asciiflow` should render the asciiflow editor and allow the user to modify and create an asciiflow directly in a vscode window.

**Comment by jgroom33** [comment]
This probably would be a separate project.
But since vscode is all nodejs based, would an extension for this tool require this to be run as a node app instead of python?

**Comment by brewingcode** [comment]
This just posted to HN today: https://news.ycombinator.com/item?id=22840295

**Comment by jgroom33** [comment]
https://marketplace.visualstudio.com/items?itemName=zenghongtu.vscode-asciiflow2
