### ISSUE TITLE
Google OAuth does not work

### ISSUE THREAD

**Issue by manizzle** [lewish/asciiflow2#138]
I cant get the OAuth integration to work.

I get the following

<img width="604" alt="Screen Shot 2019-09-30 at 2 23 10 PM" src="https://user-images.githubusercontent.com/2058626/65918217-f4e43080-e38d-11e9-8d0a-e4ed1552fa30.png">

**Comment by Qix-** [comment]
Yes there are a number of issues already open about this. :)
