### ISSUE TITLE
i want to pay but i cannot

### ISSUE THREAD

**Issue by hq9000** [lewish/asciiflow2#140]
i wish to become a paying user. Attempted several times, but couldn't.

what i keep getting is:

http://i.imgur.com/IG0X2C9.png

**Comment by Qix-** [comment]
No idea what this is; we don't charge for asciiflow. Please think twice before entering your credit card information into random websites.

**Comment by hq9000** [comment]
this stuff is in the html served:

<script type="text/javascript" src="https://code.tinypass.com/tpl/d1/tpm.js"></script>

and that seems to be what is asking for payment. You might consider removing it.

**Comment by Qix-** [comment]
Huh. @lewish what are you intentions for the tinypass stuff?

**Comment by Qix-** [comment]
Seems like something has changed.

**Comment by Qix-** [comment]
Going to close this for now; AF3 will not have any of this code in here.

Please disregard it; I've stated it a few times before, but Asciiflow is free to use.
