### ISSUE TITLE
better arrow characters

### ISSUE THREAD

**Issue by mreinstein** [lewish/asciiflow2#144]
rather than:
```
    ^
    |
    |
<---+--->
    |
    |
    v

```

give me:
```
    ▲
    |
    |
◀---+---▶
    |
    |
    ▼

```

**Comment by MMK21Hub** [comment]
Do you even know what ASCII art is?

**Comment by mreinstein** [comment]
I'm happy  to discuss the merits of github issues, but this doesn't seem like a constructive piece of feedback I can do anything with. :( It's veering into personal attack territory .

**Comment by vashnt707** [comment]
My 2 cents. Since there isn't much development activity here, non-ascii characters can bring in unnecessary complications thereby skewing and slowing down the project.

**Comment by mreinstein** [comment]
non-ascii characters already exist in ascii flow, in fact there's a dedicate mode for it. See the screen shot in https://github.com/lewish/asciiflow2/issues/145#issuecomment-644188886

**Comment by Qix-** [comment]
See https://github.com/lewish/asciiflow2/issues/145#issuecomment-644389262

**Comment by Qix-** [comment]
Merging into #143. AF3 will address this.

**Comment by MMK21Hub** [comment]
Sorry for my comment. I didn't realise that ASCIIflow has a non-ASCII mode.
