### ISSUE TITLE
Text tool cursor not visible at start of line when using Chromium

### ISSUE THREAD

**Issue by alustig3** [lewish/asciiflow2#159]
When typing in the text tool, if you move the cursor to the beginning of a line, it disappears. It would be nice to have a blinking cursor there so the user knows where they are, like when the cursor is at other positions.

I'm using Brave browser Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)

This wasn't a problem when I used Safari or Firefox.

**Comment by Qix-** [comment]
Definitely, I think this is a browser bug. I've had similar weirdness happen myself.

**Comment by lewish** [comment]
Hi there, text tool has been completely revamped to write inside the drawing itself, and it does have a cursor indicator. PTAL and let me know if this resolves the issue or if you have any other feedback!
