### ISSUE TITLE
Google-Login deactived / not possible

### ISSUE THREAD

**Issue by fnord235** [lewish/asciiflow2#161]
Just had an issue with Firefox opening the login pop up like once per second, so that it was not possible to even try to login. So I closed all tabs (without any saves, great), and re-tried with chrome. I simply can't login using google, because they have deactivated this feature for security reasons or something. The original message in German says:

"Die Anmeldung mit Google ist für diese App vorübergehend deaktiviert
 Die Verwendung von Google Log-in wurde für diese App noch nicht bestätigt."

en translation:
"Login with Google has temporarily been deactivated for this app. 
The use of Google Log-in hasn't been confirmed for this app yet"

Seems to be OAuth related. Couldn't find anything in my account settings, please fix this soon :( that'd be great, because without saving, what's the point in drawing? 

Besides of that: I just found this tool and it looks pretty useful in general, so kudos to the developers. I'm too lazy to draw by hand, but who isn't :D ..

**Comment by Qix-** [comment]
Yes, there are quite a few other tickets open about this already. It's a well known issue.

Please see #153, #138, #149, #136, etc.
