### ISSUE TITLE
Unable to save to google drive, then chaos

### ISSUE THREAD

**Issue by antony** [lewish/asciiflow2#163]
I drew a small diagram and hit the google drive diagram to save. It said some message about denying access to my google drive because asciiflow tried to access private files.

I tried with a few different accounts and got the same message.

So I hit export to try to copy the diagram into a text editor, and another google login popup appeared. I closed it. clicked my diagram - another popup. I tried to quickly copy paste and switched to my editor, and I then became bombarded with over a thousand google authentication popups, which kept spawning 2-3 per second until i had to `killall chrome` to make it stop.

so I guess the crux is, google drive authentication doesn't seem to work!

**Comment by ckittel** [comment]
Yeah, Google is currently blocking access to even log in now on asciiflow.

**Comment by lewish** [comment]
Closing this out as I'm dropping the GDrive integration in favour of local storage in the new version for now, which hopefully resolves this.
