### ISSUE TITLE
Auto Copy-to-clipboard on Export function?

### ISSUE THREAD

**Issue by samirvine** [lewish/asciiflow2#18]
This would save users from having to highlight entire output on export. Would also be a great help to mobile users.

**Comment by Qix-** [comment]
Things have changed in 6 years, thankfully. Will put this on a list for AF3.

**Comment by lewish** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/912458/109414397-953aec00-79aa-11eb-94b5-37ecd021140f.png)
