### ISSUE TITLE
License Agreement?

### ISSUE THREAD

**Issue by abarnet** [lewish/asciiflow2#31]
Is there a license agreement for this project? I really like the project, but want to make sure I know how it's licensed before I run a local version or try developing new features.

**Comment by wolfv** [comment]
I am wondering the same...

**Comment by kuy** [comment]
+1

**Comment by mattdm** [comment]
See also issue #42

**Comment by kuy** [comment]
GitHub should have *default* license for unknown license project...

**Comment by busbey** [comment]
bump. any update on choosing a license for the project?

**Comment by jseadragon** [comment]
+1

**Comment by charliewolf** [comment]
:thumbsup:

**Comment by sylvainpolletvillard** [comment]
@lewish hey, could you please add a license for AsciiFlow? Many of us would love to use your work

**Comment by Qix-** [comment]
> GitHub should have _default_ license for unknown license project...

That would be a legal nightmare. 😅 

Looks like one was added but I'm going to talk to @lewish about making it a bit more permissive for v3.

Closing as there's nothing else that's actionable.
