### ISSUE TITLE
Allow use of unicode box drawing characters for output

### ISSUE THREAD

**Issue by tal** [lewish/asciiflow2#33]
Have an export mode to allow unicode box drawing as well

http://en.wikipedia.org/wiki/Box-drawing_character

**Comment by rabin-io** [comment]
+1

**Comment by Qix-** [comment]
It's there now - go to the `?` in the top right and click "line mode" (default is "ascii mode").

**Comment by Qix-** [comment]
Closing as a duplicate of #143 as there's a bit more rich information there (though I know this was created before it).

Sorry for the noise!
