### ISSUE TITLE
tpm.js causing browser to freeze

### ISSUE THREAD

**Issue by jonathancross** [lewish/asciiflow2#39]
Browser: Chrome 44.0.2403.107 (64-bit) MAC OSX.

JS console message repeats every second, browser process uses 100% CPU until crash:

```
tpm.js:72 PARENT message received: {"s":"oauth2callback:301245870","f":"oauth2relay821844053","c":0,"a":["http://asciiflow.com?state=669359844%7C0.48452533&error_subtype=access_denied&error=immediate_failed"],"t":"301245870","l":false,"g":true,"r":"oauth2relay821844053"}
```

Notes:
- I am getting this almost anytime I switch tools, go to a new tab, then return, etc.
- I did not allow access to Google drive because permissions are too expansive.
- No third party Ad blockers, etc.

**Comment by Qix-** [comment]
Closing as I've not heard of this recently and AF3 will not be using it.

Also, sorry for the noise 5 years later :)
