### ISSUE TITLE
Arrow heads not working in line mode

### ISSUE THREAD

**Issue by sr105** [lewish/asciiflow2#41]
<img width="201" alt="screen shot 2015-10-01 at 7 51 56 pm" src="https://cloud.githubusercontent.com/assets/814760/10236618/e77f764e-6875-11e5-9e3f-b72cb5f29c34.png">
<img width="223" alt="screen shot 2015-10-01 at 7 51 33 pm" src="https://cloud.githubusercontent.com/assets/814760/10236617/e77eb376-6875-11e5-8863-617a4ba1d2c8.png">

**Comment by Qix-** [comment]
Yes this is a known issue, namely because there are no box-drawing arrow-heads in the unicode set. There will have to be an alternative.

**Comment by jaredkhan** [comment]
I've been playing with Unicode box drawing a bit lately.
The triangle characters seem to line up fairly well horizontally with the box drawing characters in tools I've used. There's an ugly gap vertically but better than nothing:

```

          ▲
          │
       ◀──┼──▶
          │
          ▼
```

**Comment by lewish** [comment]
I think this is now fixed with the new version that uses these characters by default. Please let me know if not!
