### ISSUE TITLE
Consider an open source license

### ISSUE THREAD

**Issue by mattdm** [lewish/asciiflow2#42]
This is an amazing project. I'd love to see it available as open source / free software. Would you consider adding a license to it?

See GitHub's http://choosealicense.com/ site. AGPL might be a good choice, as that asks anyone running a hosted instance to contribute changes back.

**Comment by charliewolf** [comment]
:thumbsup:

**Comment by Qix-** [comment]
Closed by #92 and a duplicate of #31 but I'll ask @lewish if he'd be willing to use a more permissive license in the new version.
