### ISSUE TITLE
moving an item ?

### ISSUE THREAD

**Issue by solyarisoftware** [lewish/asciiflow2#46]
Hi Lewis!

I LOVE! ASCIIFLow.com :)

and I just wrote a thank you in my recent project:
https://github.com/solyaris/telegram-bot-ruby-webhooks#thanks-to

Here a minor question (not a real issue):
Can I really MOVE an item (a box) ?
I'm asking because I see the button in ascciflow.com that state "Resize/move a box/line"
An I'm able to resize with success a box, but HOW I can **MOVE** ?
Maybe some CTRL/ALT keystroke command ?

Sorry for my stupid point
respect
giorgio

**Comment by rawlk** [comment]
Take a look at this. . . 
![text-move](https://user-images.githubusercontent.com/5741202/52587125-f365f800-2dfe-11e9-9127-7496f775c693.gif)


Using the "cursor" tool to highlight and then drag the text
