### ISSUE TITLE
Google Drive file list goes off-screen

### ISSUE THREAD

**Issue by bestscarper** [lewish/asciiflow2#51]
I had about 100 text files added to my Drive, and these just run off the bottom of the screen, so I can't reach my DITAA files.

**Comment by Qix-** [comment]
Not sure I understand. I realize this is a super old issue (sorry for the noise) but if you still use the tool and still run into this problem, please let me know and we can re-open and discuss :)

**Comment by bestscarper** [comment]
thanks, but i can't replicate this while Google Drive support is broken https://github.com/lewish/asciiflow2/issues/118
