### ISSUE TITLE
The v letter get transformed into ^

### ISSUE THREAD

**Issue by redochka** [lewish/asciiflow2#52]
Type v in a text box, close and open the file, the v get transformed into ^ 

hint: I noted that box containing the v letter is colored in blue..

**Comment by 4ants** [comment]
Same here.
This is a bug.

**Comment by roipoussiere** [comment]
Related issue : in lines mode, `v` and `-` characters are transformed into nothing.

**Comment by Qix-** [comment]
Duplicate of #109, has been fixed and released now :) Go check it out!
