### ISSUE TITLE
v shows up and ^

### ISSUE THREAD

**Issue by saslani** [lewish/asciiflow2#55]
I tried to import:
![expected](https://cloud.githubusercontent.com/assets/90029/13134093/3001202e-d5c8-11e5-8c31-6aef468d2a3c.png)

but got:
![actual](https://cloud.githubusercontent.com/assets/90029/13134099/49536d7a-d5c8-11e5-8603-513c15ed7f3f.png)

**Comment by iisfaq** [comment]
I have seen this too. I think that the v is used as a Vertical Line in the lines mode as that is what it draws in that mode. But in ascii mode is really should display as a v.

You will notice it is also colored the same as a line segment (silver) and not white.

**Comment by bitblitz** [comment]
+1 for this.

Thanks for AsciiFlow though - great tool!

**Comment by dundeemt** [comment]
/dev/ad0 -> fine
/dev/ad1 --> /de^/ad1

change ^ back v and then it flips back again.

**Comment by fstark** [comment]
Commenting line 337-339 of state.js fixed it for me.

    /**
     * Loads the given text into the diagram starting at the given offset (centered).
     * @param {string} value
     * @param {ascii.Vector} offset
     */
    ascii.State.prototype.fromText = function(value, offset) {
      var lines = value.split('\n');
      var middle = new ascii.Vector(0, Math.round(lines.length / 2));
      for (var j = 0; j < lines.length; j++) {
        middle.x = Math.max(middle.x, Math.round(lines[j].length / 2));
      }
      for (var j = 0; j < lines.length; j++) {
        var line = lines[j];
        for (var i = 0; i < line.length; i++) {
          var char = line.charAt(i);
          // Convert special output back to special chars.
          // TODO: This is a horrible hack, need to handle multiple special chars
          // correctly and preserve them through line drawing etc.
          if (SPECIAL_VALUES.indexOf(char)  != -1) {
            char = SPECIAL_VALUE;
          }
          // if (ALT_SPECIAL_VALUES.indexOf(char) != -1) {
          //   char = ALT_SPECIAL_VALUE;
          // }
          this.drawValue(new ascii.Vector(i, j).add(offset).subtract(middle), char);
        }
      }
    };

I am not sure of what is going on, and I don't really understand why this was there in the first place...

**Comment by fspafford** [comment]
I also see this problem. And thanks for creating the tool.
