### ISSUE TITLE
ctrl to move does not work on OS X

### ISSUE THREAD

**Issue by erpel** [lewish/asciiflow2#57]
OS X captures ctrl on the system level and performs a context click (right click) when the mouse button goes down.

I believe it should be possible to use the Cmd key on OS X for moving.

**Comment by jguice** [comment]
@erpel have you tried holding `[cmd]` while clicking and dragging?  It's working for me in Chrome 49.0.2623.112 (64-bit).

The help does need updated though. :wink:

**Comment by erpel** [comment]
I just tried again in Safari and Firefox. In both CMD did nothing unfortunately. Maybe Chrome is doing some conversion automatically.

**Comment by jguice** [comment]
Safari Version 9.1 (11601.5.17.1) works for me too (OS X 10.11.4 (15E65)).

I press and hold `[CMD]`, then click (hold) and drag the canvas around (clicking an empty spot).  Also working with 3-finger drag on my trackpad.

**Comment by erpel** [comment]
Anyway, works now. Thanks again for the cool project :D
