### ISSUE TITLE
freehand drawing character preference doesn't work.

### ISSUE THREAD

**Issue by davethepom** [lewish/asciiflow2#59]
Draw freehand. Press a character on the keyboard and draw with it.

It doesn't work for me. I type a character & then draw and it's just a blanc "block" cursor. If I accept the default "x" xharacter, that's fine. I'd like to use a full stop preferably. Interestingly, the old version of the app works fine!.
Hope this hasn't already been filed.
Rgds Dave S

**Comment by Qix-** [comment]
I know this is 4 years old (sorry for the noise) but it seems to be working fine for me.

![image](https://user-images.githubusercontent.com/885648/84712486-02b40300-af69-11ea-8347-ab1db9266593.png)

If you still use the tool and still run into this issue, let me know here and we can re-open and address it properly for the new version :)
