### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [lewish/asciiflow2#60]
While this is not exactly an issue, I feel some keyboard shortcuts would be of great help. 

Also, while you're at it, I think you should disable the Chrome shortcut for going back a page by swiping with 2 fingers, as this often leads to me losing work.

**Comment by enyo** [comment]
Shortcuts would be really great.

**Comment by Qix-** [comment]
Duplicate of #90. Will open a new ticket about the two-finger swipe as it has bitten me, too.
