### ISSUE TITLE
not support encoding 'GBK'

### ISSUE THREAD

**Issue by jptiancai** [lewish/asciiflow2#61]
![qq 20160531174415](https://cloud.githubusercontent.com/assets/1734718/15670313/5a63fe82-2757-11e6-82a8-1628efcbeef1.png)

**Comment by SteamedFish** [comment]
I don't think it's related to encoding. it is related to the visual length of Chinese characters.

**Comment by Qix-** [comment]
Yep, duplicate of #85.
