### ISSUE TITLE
question: CLI or JS API

### ISSUE THREAD

**Issue by jasonkarns** [lewish/asciiflow2#63]
Is there a JS API or CLI for taking a plain text ascii file and generating an image?

**Comment by Joedang** [comment]
You could use ImageMagick (and `fold`, if necessary).

For example, if I start with this text file, `face.txt`:
```
+-----------------+
|                 |
|  +--+    +---+  |
|  +--+    +---+  |
|                 |
| +            +  |
| +------------+  |
|                 |
+-----------------+
```
and run this:
```bash
$ convert -size 1000x1000 xc:white -gravity northwest -font FreeMono-Regular -annotate 0 "$(cat face.txt)" -trim ascii.png
```
I get this image:
![ascii](https://user-images.githubusercontent.com/16861664/27715988-cac2d2c4-5cef-11e7-8c37-7c33ca2be1c2.png)

**Comment by dwesely** [comment]
You might want to check out this CoffeeScript tool for converting ASCII drawings to line drawing image files: https://github.com/dbushong/shaky

(That GitHub page linked to the demo)

**Comment by Qix-** [comment]
Check out #45 :) That tool should do what you want.
