### ISSUE TITLE
Asciiflow.com is served over HTTP

### ISSUE THREAD

**Issue by igor47** [lewish/asciiflow2#64]
<img width="996" alt="screen shot 2016-07-13 at 7 51 44 pm" src="https://cloud.githubusercontent.com/assets/200575/16826576/439f24d0-4933-11e6-8800-be5611c9d53e.png">

**Comment by igor47** [comment]
your cert is for `*.appspot.com` which will work for `anything.appspot.com` but won't work for `anything.something.appspot.com`

**Comment by Qix-** [comment]
Agreed, this is still an issue I hope to fix with AF3 and Github pages.

Will tag to make sure it's addressed properly.

Sorry for the noise 4 years later! :)

**Comment by webmaster777** [comment]
GH pages allow https with custom domains. See https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https and https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by lewish** [comment]
Should be fixed now!
