### ISSUE TITLE
Feature: Banner text

### ISSUE THREAD

**Issue by alanwevans** [lewish/asciiflow2#66]
Instead of just inserting single character fronts, use banner style fonts like at [http://patorjk.com/](http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20)

You can successfully paste things in now, but integration would be slick.

<pre>
+----------------------------------+
|                                  |
|  ___________              __     |
|  \__    ___/___   _______/  |_   |
|    |    |_/ __ \ /  ___/\   __\  |
|    |    |\  ___/ \___ \  |  |    |
|    |____| \___  >____  > |__|    |
|               \/     \/          |
|                                  |
+----------------------------------+
</pre>

**Comment by Qix-** [comment]
Licensing is an issue here and pasting text works fine. This would be [gold plating](https://en.wikipedia.org/wiki/Gold_plating_(project_management)) at best, unfortunately.

Going to close; sorry for the noise 4 years later!
