### ISSUE TITLE
Support export SVG

### ISSUE THREAD

**Issue by J-F-Liu** [lewish/asciiflow2#70]
I discovered a project which can be used to convert ASCII art to SVG:
https://github.com/ivanceras/svgbob

**Comment by Qix-** [comment]
Thanks for the link, it's a cool project indeed!

Unfortunately this is in Rust so I doubt it would be possible across environments.

There is already a (very small, contingent) item on the "stretch goals" list to include such behavior, so maybe I'll re-visit the linked project later on.

However, for now I have to close this. Sorry for the noise 4 years later.

**Comment by ssokolow** [comment]
> so I doubt it would be possible across environments

Would you mind elaborating on that? It [runs in the browser via WebAssembly](https://ivanceras.github.io/svgbob-editor/) and Node.js also supports WebAssembly modules.

Even if *using* svgbob isn't a viable option, making an effort to match its interpretations so ASCIIFlow drawings can be pasted into Markdown or ReStructuredText or whatever and then rendered to SVG by the static generation process without needing manual fix-ups would be desirable.
