### ISSUE TITLE
Feature: More Intelligent Shapes Please, Curves

### ISSUE THREAD

**Issue by solvingj** [lewish/asciiflow2#71]
I love this application concept. 

I have lots of visio experience.  One thing I think is fundamental is giving some elegant solution to shapes with curved lines using forward and backslashes.  I'm sure adding the feature to enable dragging ovals/circles is not trivial, but that is my top suggestion.

**Comment by Qix-** [comment]
Hi, sorry for the noise 4 years later :)

Unfortunately the algorithms for this sort of thing are quite limited when it comes to text. Perhaps this can be re-visited after AF3 is released, but for now I'm going to close this.

Thanks for the suggestion :)
