### ISSUE TITLE
click and write text

### ISSUE THREAD

**Issue by MasseGuillaume** [lewish/asciiflow2#84]
I think it would be a bit faster if you could click on a cell and enter text directly, bypassing the text button (A).

Amazing project by the way!

**Comment by Qix-** [comment]
This would conflict with #90 but I think double-clicking would be an acceptable alternative.

**Comment by Qix-** [comment]
Given more thought, I think this is [gold plating](https://en.wikipedia.org/wiki/Gold_plating_(project_management)) and not really something I think will improve efficiency.

Going to close for now. Sorry for the noise three years later!
