### ISSUE TITLE
Build issues with compile.sh

### ISSUE THREAD

**Issue by wadester** [lewish/asciiflow2#91]
Great program.  I am trying to build it so I can run it on my separate network, but the build is failing.

When I run ./compile.sh I get:

js-lib/state.js:323: ERROR - variable ascii is undeclared
    var middle = new ascii.Vector(0, Math.round(lines.length / 2));
                     ^^^^^
js-lib/state.js:334: ERROR - variable SPECIAL_VALUES is undeclared
        if (SPECIAL_VALUES.indexOf(char)  != -1) {
            ^^^^^^^^^^^^^^
js-lib/state.js:335: ERROR - variable SPECIAL_VALUE is undeclared
          char = SPECIAL_VALUE;
                 ^^^^^^^^^^^^^

Computer is:  CentOS 6.9 with updates, Oracle Java 1.8 (or OpenJDK 1.7), 64-bit.

Can anyone help?

**Comment by BlackBeatles** [comment]
@wadester have you deal your problem? i have the same problem

**Comment by wadester** [comment]
I haven't found a fix and am working on other issues with my software.  I would like to run AsciiFlow on my private network so need the fix, but very, very low priority.

**Comment by xkpd3** [comment]
Same issue here. FreeBSD 11, OpenJDK 1.8.0_131.

**Comment by andrewbrady** [comment]
Same issue, Can you give a working OS/Java that will work so I can work backwards to assist?

**Comment by allanhaywood** [comment]
Any idea when the pull request will get approved and merged?

**Comment by Qix-** [comment]
I don't see this problem anymore, going to optimistically close it.

Please let me know if that's not the case and I'll address it :)
