### ISSUE TITLE
Conservative Google Drive access

### ISSUE THREAD

**Issue by lhunath** [lewish/asciiflow2#95]
Google Drive access authorization should be limited to only the files created by and opened with asciiflow, not the full scope of all of a user's Drive files.

**Comment by Qix-** [comment]
I'll take a look into this when I get around to fixing G-Drive.

**Comment by Qix-** [comment]
Getting around to tidying up a bit (sorry for the noise 3 years later) and decided to do a cursory look into this:

`https://www.googleapis.com/auth/drive.file` is a scope that does exactly what you're describing, so yes, this is possible.

**Comment by lewish** [comment]
Google drive integration is dead.
