### ISSUE TITLE
Resizing a box deletes two sides in locally hosted version

### ISSUE THREAD

**Issue by jbwiv** [lewish/asciiflow2#99]
If I draw a box in the hosted edition, I can then click the resize button and resize it. However, if I compile locally and run, this:

+-------+
|             |
|             |
|             |
+-------+

Becomes this:

+
|
|
|
+-------+

Is the current code running at asciiflow.com the same as master?

Thanks!

**Comment by diversenok** [comment]
Same here. I've fixed it for myself by replacing *js-compiled.js* from the repo with [js-compiled.js](http://asciiflow.com/js-compiled.js) from the website.

**Comment by whj2819** [comment]
Thank you.

**Comment by Qix-** [comment]
Just fixed, go check it out :)
